# Generated by Django 3.0.3 on 2020-02-16 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parsing', '0005_site_is_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='is_running',
        ),
        migrations.AlterField(
            model_name='site',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RunningTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала задачи')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parsing.Site')),
            ],
        ),
    ]
