# Generated by Django 3.0.2 on 2020-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseurl',
            name='identifier_type',
            field=models.IntegerField(choices=[(0, 'id'), (1, 'class'), (2, 'xpath'), (3, 'tag')]),
        ),
        migrations.AlterField(
            model_name='baseurl',
            name='parser',
            field=models.IntegerField(choices=[(0, 'Selenium'), (1, 'Requests')]),
        ),
    ]
