# Generated by Django 3.0.2 on 2020-01-20 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parsing', '0003_auto_20200120_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
