# Generated by Django 3.0.3 on 2020-04-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200411_1226'),
        ('parsing', '0011_move_price_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningtask',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время завершения задачи'),
        ),
        migrations.AddField(
            model_name='runningtask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность задачи'),
        ),
        migrations.AlterField(
            model_name='runningtask',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_tasks', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='runningtask',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала задачи'),
        ),
    ]
