# Generated by Django 3.0.3 on 2020-04-12 12:37

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_add_verbose_names_and_meta'),
        ('parsing', '0012_auto_20200411_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningtask',
            options={'verbose_name': 'Задача для обновления данных о товаре', 'verbose_name_plural': 'Задачи для обновления данных о товаре'},
        ),
        migrations.AlterField(
            model_name='runningtask',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_tasks', to='product.Product', verbose_name='Ссылка на товар'),
        ),
    ]
